### PR TITLE
Add typing to ``brain_dataclasses``

### PR DESCRIPTION
**Pull request by DanielNoord**
## Steps

- [x] Write a good description on what the PR does.

## Description

This does not fix everything as I have left some of the non-trivial cases for a separate PR.

I have one question that needs to be answered before this can be merged.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

### CODE REVIEW

File: astroid/brain/brain_dataclasses.py [hunk 1]
```diff
@@ -190,12 +195,12 @@ def _generate_dataclass_init(assigns: List[AnnAssign]) -> str:
             if isinstance(value, Call) and _looks_like_dataclass_field_call(
                 value, check_scope=False
             ):
-                result = _get_field_default(value)
-
-                default_type, default_node = result
+                default_type, default_node = _get_field_default(value)
```
Comment (DanielNoord) [inline astroid/brain/brain_dataclasses.py:198]: @cdce8p For some reason I can't seem to restrict the return type of `_get_field_default` and let `mypy` know about this.

I tried `Union[Tuple[None, None], Tuple[str, NodeNG]]` (and the necessary change to the method) as return type annotation, but then `mypy` doesn't recognise that `if default_type == "default"` then `default_node` is a `NodeNG`. I have tried other things such as working but a type alias but I couldn't get it to work. Searching for "mypy union return distinguish tuple constraints" etc also didn't return anything.

Do you have any good ideas or are these `assert`'s the best solution here?

File: astroid/brain/brain_dataclasses.py [hunk 2]
```diff
@@ -264,6 +271,7 @@ def _looks_like_dataclass_decorator(
     """
     if isinstance(node, Call):  # decorator with arguments
         node = node.func
+
```
Comment (DanielNoord) [inline astroid/brain/brain_dataclasses.py:274]:
```suggestion
```

File: astroid/brain/brain_dataclasses.py (hunk 1 above)
Comment (tushar-deepsource) [reply astroid/brain/brain_dataclasses.py:198]: Here's a neat way to do that:

```python
result = _get_field_default(value)
if result != (None, None):
    default_type, default_node = result
    # Here mypy should know that default_type is a str, and default_node is a NodeNG
```

Comment (tushar-deepsource) [reply astroid/brain/brain_dataclasses.py:198]: You could also modify the return type of `_get_field_value` to return `None` instead of `None, None`. Might make it better?

Comment (DanielNoord) [reply astroid/brain/brain_dataclasses.py:198]:
```python
                result = _get_field_default(value)
                if result != (None, None):
                    default_type, default_node = result
                    if default_type == "default":
                        param_str += f" = {default_node.as_string()}"  # L202
                    elif default_type == "default_factory":
                        param_str += f" = {DEFAULT_FACTORY}"
                        assignment_str = (
                            f"self.{name} = {default_node.as_string()} "  # L206
                            f"if {name} is {DEFAULT_FACTORY} else {name}"
                        )
```

Still gives me:
```shell
astroid/brain/brain_dataclasses.py:202: error: Item "None" of "Optional[NodeNG]" has no attribute "as_string"  [union-attr]
astroid/brain/brain_dataclasses.py:206: error: Item "None" of "Optional[NodeNG]" has no attribute "as_string"  [union-attr]
```

Am I missing something?

Comment (tushar-deepsource) [reply astroid/brain/brain_dataclasses.py:198]: Did you change the return type for that function to `Union[Tuple[None, None], Tuple[str, NodeNG]]`?

Comment (DanielNoord) [reply astroid/brain/brain_dataclasses.py:198]: Yeah.

Diff:
<details>
diff --git a/astroid/brain/brain_dataclasses.py b/astroid/brain/brain_dataclasses.py
index b34f1aeff..d239806c5 100644
--- a/astroid/brain/brain_dataclasses.py
+++ b/astroid/brain/brain_dataclasses.py
@@ -7,7 +7,7 @@ Support both built-in dataclasses and pydantic.dataclasses. References:
 - https://docs.python.org/3/library/dataclasses.html
 - https://pydantic-docs.helpmanual.io/usage/dataclasses/
 """
-from typing import FrozenSet, Generator, List, Optional, Tuple
+from typing import FrozenSet, Generator, List, Optional, Tuple, Union
 
 from astroid import context, inference_tip
 from astroid.builder import parse
@@ -195,17 +195,18 @@ def _generate_dataclass_init(assigns: List[AnnAssign]) -> str:
             if isinstance(value, Call) and _looks_like_dataclass_field_call(
                 value, check_scope=False
             ):
-                default_type, default_node = _get_field_default(value)
-                if default_type == "default":
-                    assert default_node
-                    param_str += f" = {default_node.as_string()}"
-                elif default_type == "default_factory":
-                    assert default_node
-                    param_str += f" = {DEFAULT_FACTORY}"
-                    assignment_str = (
-                        f"self.{name} = {default_node.as_string()} "
-                        f"if {name} is {DEFAULT_FACTORY} else {name}"
-                    )
+                result = _get_field_default(value)
+                if result != (None, None):
+                    default_type, default_node = result
+                    if default_type == "default":
+                        param_str += f" = {default_node.as_string()}"
+                    elif default_type == "default_factory":
+                        param_str += f" = {DEFAULT_FACTORY}"
+                        assignment_str = (
+                            f"self.{name} = {default_node.as_string()} "
+                            f"if {name} is {DEFAULT_FACTORY} else {name}"
+                        )
+
             else:
                 param_str += f" = {value.as_string()}"
 
@@ -335,7 +336,9 @@ def _looks_like_dataclass_field_call(node: Call, check_scope: bool = True) -> bo
     return inferred.name == FIELD_NAME and inferred.root().name in DATACLASS_MODULES
 
 
-def _get_field_default(field_call: Call) -> Tuple[str, Optional[NodeNG]]:
+def _get_field_default(
+    field_call: Call,
+) -> Union[Tuple[None, None], Tuple[str, NodeNG]]:
     """Return a the default value of a field call, and the corresponding keyword argument name.
 
     field(default=...) results in the ... node
@@ -363,7 +366,7 @@ def _get_field_default(field_call: Call) -> Tuple[str, Optional[NodeNG]]:
         new_call.postinit(func=default_factory)
         return "default_factory", new_call
 
-    return "", None
+    return None, None
 
 
 def _is_class_var(node: Optional[NodeNG]) -> bool:
</details>

Comment (DanielNoord) [reply astroid/brain/brain_dataclasses.py:198]: The following diff works, but it feels weird to need to do an additional assignment to help `mypy` infer the type:
It should be able to link the `None` to the `None` and `str` to `NodeNG`.

```diff
diff --git a/astroid/brain/brain_dataclasses.py b/astroid/brain/brain_dataclasses.py
index b34f1aeff..648fdb827 100644
--- a/astroid/brain/brain_dataclasses.py
+++ b/astroid/brain/brain_dataclasses.py
@@ -7,7 +7,7 @@ Support both built-in dataclasses and pydantic.dataclasses. References:
 - https://docs.python.org/3/library/dataclasses.html
 - https://pydantic-docs.helpmanual.io/usage/dataclasses/
 """
-from typing import FrozenSet, Generator, List, Optional, Tuple
+from typing import FrozenSet, Generator, List, Optional, Tuple, Union
 
 from astroid import context, inference_tip
 from astroid.builder import parse
@@ -195,17 +195,17 @@ def _generate_dataclass_init(assigns: List[AnnAssign]) -> str:
             if isinstance(value, Call) and _looks_like_dataclass_field_call(
                 value, check_scope=False
             ):
-                default_type, default_node = _get_field_default(value)
-                if default_type == "default":
-                    assert default_node
-                    param_str += f" = {default_node.as_string()}"
-                elif default_type == "default_factory":
-                    assert default_node
-                    param_str += f" = {DEFAULT_FACTORY}"
-                    assignment_str = (
-                        f"self.{name} = {default_node.as_string()} "
-                        f"if {name} is {DEFAULT_FACTORY} else {name}"
-                    )
+                result = _get_field_default(value)
+                if result:
+                    default_type, default_node = result
+                    if default_type == "default":
+                        param_str += f" = {default_node.as_string()}"
+                    elif default_type == "default_factory":
+                        param_str += f" = {DEFAULT_FACTORY}"
+                        assignment_str = (
+                            f"self.{name} = {default_node.as_string()} "
+                            f"if {name} is {DEFAULT_FACTORY} else {name}"
+                        )
             else:
                 param_str += f" = {value.as_string()}"
 
@@ -335,7 +335,9 @@ def _looks_like_dataclass_field_call(node: Call, check_scope: bool = True) -> bo
     return inferred.name == FIELD_NAME and inferred.root().name in DATACLASS_MODULES
 
 
-def _get_field_default(field_call: Call) -> Tuple[str, Optional[NodeNG]]:
+def _get_field_default(
+    field_call: Call,
+) -> Optional[Tuple[str, NodeNG]]:
     """Return a the default value of a field call, and the corresponding keyword argument name.
 
     field(default=...) results in the ... node
@@ -363,7 +365,7 @@ def _get_field_default(field_call: Call) -> Tuple[str, Optional[NodeNG]]:
         new_call.postinit(func=default_factory)
         return "default_factory", new_call
 
-    return "", None
+    return None
 
 
 def _is_class_var(node: Optional[NodeNG]) -> bool:
```

Comment (tushar-deepsource) [reply astroid/brain/brain_dataclasses.py:198]: Yeah. Possibly mypy bug.

But I prefer this solution, as we were essentially returning two sentinels in the previous case.

File: astroid/brain/brain_dataclasses.py [hunk 3]
```diff
@@ -325,7 +335,9 @@ def _looks_like_dataclass_field_call(node: Call, check_scope: bool = True) -> bo
     return inferred.name == FIELD_NAME and inferred.root().name in DATACLASS_MODULES
 
 
-def _get_field_default(field_call: Call) -> Tuple[str, Optional[NodeNG]]:
+def _get_field_default(
+    field_call: Call,
+) -> Optional[Tuple[str, NodeNG]]:
```
Comment (Pierre-Sassoulas) [inline astroid/brain/brain_dataclasses.py:340]:
```suggestion
def _get_field_default(field_call: Call) -> Optional[Tuple[str, NodeNG]]:
```

**Review by Pierre-Sassoulas — APPROVED** [review]
👍 Thank you @tushar-deepsource for the thorough review !

**Comment by cdce8p** [comment]
I still plan to get to it, sorry for the delay.

**Comment by Pierre-Sassoulas** [comment]
No worry, there's still the issue with python 3.10 to fix before merging anyway. I don't know what could be happening, maybe a deprecation in setuptools/distutils ?

**Comment by DanielNoord** [comment]
@cdce8p No rush! We're all still volunteers.

If I can be so bold, could I ask you to put https://github.com/PyCQA/pylint/pull/5221 on the top of your to-do list? We recently got a new issue about it and it blocks https://github.com/PyCQA/pylint/pull/3704 which would be good to clean up from our open PR list. As I said, no rush, just a possible rearrangement of todo's 😄

File: astroid/brain/brain_dataclasses.py [hunk 4]
```diff
@@ -243,15 +248,17 @@ def infer_dataclass_field_call(
     if not isinstance(node.parent, (AnnAssign, Assign)):
         raise UseInferenceDefault
     field_call = node.parent.value
```
Comment (cdce8p) [inline astroid/brain/brain_dataclasses.py:250]: Isn't `node.parent.value == node`? `node` can't be `node.parent.target(s)` as it's not possible to assign something to `Call` nodes. Maybe it could make sense to substitute all `field_call` names with `node` or at least at `cast(Call, ...) here?

**Review by cdce8p — CHANGES_REQUESTED** [review]

File: astroid/brain/brain_dataclasses.py (hunk 4 above)
Comment (DanielNoord) [reply astroid/brain/brain_dataclasses.py:250]: Good catch! Changed!

File: astroid/brain/brain_dataclasses.py [hunk 5]
```diff
@@ -325,7 +335,7 @@ def _looks_like_dataclass_field_call(node: Call, check_scope: bool = True) -> bo
     return inferred.name == FIELD_NAME and inferred.root().name in DATACLASS_MODULES
 
 
-def _get_field_default(field_call: Call) -> Tuple[str, Optional[NodeNG]]:
+def _get_field_default(field_call: Call) -> Optional[Tuple[str, NodeNG]]:
```
[the remark this answers is not in the document]
Comment (DanielNoord) [reply astroid/brain/brain_dataclasses.py:338]: This is creating:
```shell
astroid/brain/brain_dataclasses.py:369: error: Incompatible return value type (got "Tuple[str, NodeNG]", expected "Union[None, Tuple[Literal['default'], NodeNG], Tuple[Literal['default_factory'], Call]]")  [return-value]
astroid/brain/brain_dataclasses.py:378: error: Incompatible return value type (got "Tuple[str, Call]", expected "Union[None, Tuple[Literal['default'], NodeNG], Tuple[Literal['default_factory'], Call]]")  [return-value]
```

File: astroid/brain/brain_dataclasses.py [hunk 6]
```diff
@@ -142,6 +144,9 @@ def _check_generate_dataclass_init(node: ClassDef) -> bool:
 
     found = None
 
+    # Since this is a dataclass it should have at least one decorator
+    assert node.decorators
```
[the remark this answers is not in the document]
Comment (DanielNoord) [reply astroid/brain/brain_dataclasses.py:148]: I'm wondering if we should make an instance for `dataclass` like I did for `NamedTuple` in https://github.com/PyCQA/astroid/pull/1306.
That would also allow setting `decorators`. For now, I have removed the assert until we find a more permanent solution.

File: astroid/brain/brain_dataclasses.py (hunk 5 above)
[the remark this answers is not in the document]
Comment (cdce8p) [reply astroid/brain/brain_dataclasses.py]: It does work with the latest mypy version `0.930`

[the remark this answers is not in the document]
Comment (DanielNoord) [reply astroid/brain/brain_dataclasses.py]: Ah, my bad!

File: astroid/brain/brain_dataclasses.py [hunk 7]
```diff
@@ -330,7 +342,11 @@ def _looks_like_dataclass_field_call(node: Call, check_scope: bool = True) -> bo
     return inferred.name == FIELD_NAME and inferred.root().name in DATACLASS_MODULES
 
 
-def _get_field_default(field_call: Call) -> Tuple[str, Optional[NodeNG]]:
+def _get_field_default(
+    field_call: Call,
+) -> Union[
+    None, Tuple[Literal["default"], NodeNG], Tuple[Literal["default_factory"], Call]
+]:
```
Comment (cdce8p) [inline astroid/brain/brain_dataclasses.py:349]: I could be worth creating an Alias for it. Even if for nothing else than readability.

File: astroid/brain/brain_dataclasses.py (hunk 6 above)
[the remark this answers is not in the document]
Comment (cdce8p) [reply astroid/brain/brain_dataclasses.py]: I'm not sure yet if a separate instance would provide much benefit. Let's leave this as is then until I had time to look at #1306 and we decided how to proceed.

File: astroid/brain/brain_dataclasses.py [hunk 8]
```diff
@@ -36,6 +37,15 @@
...
 from astroid.util import Uninferable
 
+if sys.version_info >= (3, 8):
+    from typing import Literal
+else:
+    from typing_extensions import Literal
+
+FieldDefaultReturn = Union[
+    None, Tuple[Literal["default"], NodeNG], Tuple[Literal["default_factory"], Call]
+]
```
Comment (cdce8p) [inline astroid/brain/brain_dataclasses.py:47]:
```suggestion
_FieldDefaultReturn = Union[
    None, Tuple[Literal["default"], NodeNG], Tuple[Literal["default_factory"], Call]
]
```

File: astroid/brain/brain_dataclasses.py [hunk 9]
```diff
@@ -330,7 +346,7 @@ def _looks_like_dataclass_field_call(node: Call, check_scope: bool = True) -> bo
     return inferred.name == FIELD_NAME and inferred.root().name in DATACLASS_MODULES
 
 
-def _get_field_default(field_call: Call) -> Tuple[str, Optional[NodeNG]]:
+def _get_field_default(field_call: Call) -> FieldDefaultReturn:
```
Comment (cdce8p) [inline astroid/brain/brain_dataclasses.py:349]:
```suggestion
def _get_field_default(field_call: Call) -> _FieldDefaultReturn:
```

**Review by cdce8p — APPROVED** [review]
Looks good! One last comment, can be merged afterwards IMO.
Next up https://github.com/PyCQA/pylint/pull/5221
